"""Pydantic schemas for request/response validation."""

from app.schemas.skill import (
    SkillCreate,
    SkillResponse,
    SkillXPLogCreate,
    SkillXPLogResponse,
)
from app.schemas.goal import (
    GoalCreate,
    GoalUpdate,
    GoalResponse,
    GoalProgressCreate,
    GoalProgressResponse,
)
from app.schemas.chat import (
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ChatStreamEvent,
)
from app.schemas.cost import (
    APIUsageRecord,
    BudgetResponse,
    CostEstimates,
    DailyUsageResponse,
    OperationBreakdown,
    UsageHistoryResponse,
)
from app.schemas.agents import (
    AgentCapability,
    AgentConversation,
    AgentInfo,
    AgentInfoDetailed,
    AgentMessage,
    AgentStatus,
    AgentWebSocketMessage,
    AuditAction,
    AuditLogEntry,
    AuditLogResponse,
    ChatRequest as AgentChatRequest,
    ChatResponse as AgentChatResponse,
    CollaborationRequest,
    CollaborationSession,
    DelegationRequest,
    DelegationResponse,
    TaskInfo,
    TaskPriority,
    TaskStatus,
    UltronExecuteRequest,
    UltronExecuteResponse,
    UltronMonitoringStatus,
    UltronOptimizeRequest,
    UltronPlanRequest,
    UltronPlanResponse,
    UltronPlanStep,
    UltronSuggestion,
)

__all__ = [
    "SkillCreate",
    "SkillResponse",
    "SkillXPLogCreate",
    "SkillXPLogResponse",
    "GoalCreate",
    "GoalUpdate",
    "GoalResponse",
    "GoalProgressCreate",
    "GoalProgressResponse",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamEvent",
    "APIUsageRecord",
    "BudgetResponse",
    "CostEstimates",
    "DailyUsageResponse",
    "OperationBreakdown",
    "UsageHistoryResponse",
    # Agent schemas
    "AgentCapability",
    "AgentConversation",
    "AgentInfo",
    "AgentInfoDetailed",
    "AgentMessage",
    "AgentStatus",
    "AgentWebSocketMessage",
    "AuditAction",
    "AuditLogEntry",
    "AuditLogResponse",
    "AgentChatRequest",
    "AgentChatResponse",
    "CollaborationRequest",
    "CollaborationSession",
    "DelegationRequest",
    "DelegationResponse",
    "TaskInfo",
    "TaskPriority",
    "TaskStatus",
    # Ultron schemas
    "UltronExecuteRequest",
    "UltronExecuteResponse",
    "UltronMonitoringStatus",
    "UltronOptimizeRequest",
    "UltronPlanRequest",
    "UltronPlanResponse",
    "UltronPlanStep",
    "UltronSuggestion",
]
